### PR TITLE
Benjibranch

### PR DESCRIPTION
**Pull request by Orbitalben**
created the patch post, delete post

### CODE REVIEW

**Comment by fredgenske** [comment]
Hey Benji, are you working on any thing today?  I know Dave is working on some things.  I'm busy this morning but will be back at it this afternoon noon.

I'm sure we are duplicating some things, but it will be good practice.



________________________________

**Comment by Orbitalben** [comment]
I made the delete, edit and make posts pages but I accidentally messed up the pull from the master yesterday and had to work through that. They pages should be merged now and I'm just going through  your pull request and also trying to see how I can link the delete and edit functions into the post page. Or maybe into the single post page. If you have any suggestions I'd welcome them.

**Comment by Orbitalben** [comment]
I created the form for the new posts but I can't seem to get it to show up in the app. I imported it but I don't know what I'm doing wrong.

**Comment by fredgenske** [comment]
Did you add it as a route in app.jsx?



________________________________

**Comment by Orbitalben** [comment]
Pretty  sure I did. I'll  have to double check but I'm that was one of the
first things I did to fix it.

**Comment by fredgenske** [comment]
Are you saying that it doesn't show up even if you go directly to /makeposts, or the link in the sidebar doesn't show up?

I just pulled the master and went to http://localhost:{YOUR LOCAL PORT}/makeposts<http://localhost:5173/makeposts> and the form shows up, but I don't see a link to make posts on the sidebar.



________________________________

**Pull request closed without merging**
